version: "2"
services:
  samba:
    image: lordpedal/samba
    container_name: Samba
    volumes:
      - '~/docker/samba/compartido:/lordpedal'
      - '~/docker/samba/smb.conf:/etc/samba/smb.conf'
    ports:
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    restart: always
    networks:
      - ldap

networks:
  ldap:
    name: ldap_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1

